version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/app
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  hooks:
    BeforeInstall:
      - location: scripts/beforeInstall.bash
    AfterInstall:
      - location: scripts/stop.sh
        timeout: 60
        runas: ubuntu
    ApplicationStart:
      - location: scripts/start.sh
        timeout: 60
        runas: ubuntu