name: Java CI with Gradle

on:
  push:
    branches: [ "feature-chat-CtoC" ]
env:
  S3_BUCKET_NAME: hyelin-ali-deploy
  CODE_DEPLOY_APPLICATION_NAME: bidpanda-deploy
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: bidpanda-deploy-cicd
  RESOURCE_PATH: ./src/main/resources/application.yaml

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - uses: actions/checkout@v3
      
      # JDK 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # (2.5) environment 세팅
      - name: Set yml file
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ env.RESOURCE_PATH }}
        env:
          cloud.aws.credentials.accessKey: ${{ secrets.AWS_ACCESS_KEY }}
          cloud.aws.credentials.secretKey: ${{ secrets.AWS_SECRET_KEY }}
          cloud.aws.s3.bucket: ${{secrets.AWS_S3_BUCKET}}
          spring.datasource.url: ${{ secrets.DB_URL }}
          spring.datasource.username: ${{ secrets.DB_USERNAME }}
          spring.datasource.password: ${{ secrets.DB_PASSWORD }}
          spring.data.redis.host: ${{ secrets.REDIS_HOST }}
          spring.data.redis.port: ${{ secrets.REDIS_PORT }}
          spring.mail.username: ${{ secrets.MAIL_USERNAME }}
          spring.mail.password: ${{ secrets.MAIL_PASSWORD }}
          jwt.secret.key: ${{ secrets.JWT_SECRET_KEY }}

      # gradlew 실행 권한 변경
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      # gradle 빌드, 테스트 제외하고 실행
      - name: Build with Gradle
        run : ./gradlew clean build -x test
#        run: ./gradlew build
#        shell: bash

      # 전송할 파일을 담을 디렉토리 생성
      - name: Make Directory for deliver
        run: mkdir deploy

      # Jar 파일 Copy
      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy/

      # check files
      - name: check files
        run: ls -al ./deploy

      # bidpanda.jar로 파일명 변경
      - name: change name to bidpanda.jar
        run: mv ./deploy/*.jar ./deploy/bidpanda.jar

      # jar file 권한 755 부여
      - name: chmode 755
        run: sudo chmod 755 ./deploy/bidpanda.jar

      #appspec 파일 copy
      - name : Copy appspec.yml
        run: cp ./appspec.yml ./deploy/
        
      # script files 복사
      - name: Copy script
        run: cp ./scripts/*.sh ./deploy

      # 압축파일 형태로 전달
      - name: Make zip file
        run: zip -r -qq -j ./bidpanda-build.zip ./deploy

        # S3 Bucket으로 copy
      - name: Deliver to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 cp --region ap-northeast-2 --acl private ./bidpanda-build.zip s3://$S3_BUCKET_NAME/

        # Deploy
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name ${{env.CODE_DEPLOY_APPLICATION_NAME}} \
          --deployment-group-name ${{env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME}} \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=bidpanda-build.zip \
          --region ap-northeast-2